### ISSUE TITLE
Cannot run simulations_main.r

### ISSUE THREAD

**Issue by amiloudij** [ajmolstad/MTeQTLResults#1]
The file genotype_ensg00000160284.rds could not be found.
Line 47 and 48

**Comment by ajmolstad** [comment]
Here, you will have to replace this file with your own genotype matrix (n subjects by p genotypes). The data used to perform the simulations in our article are from GTEx, and thus cannot be shared. Sorry this was not made more clear in the documentation.

**Comment by amiloudij** [comment]
Where can i find a public genotype files .RDS? I really want to run that script!! (Simulations_main.r)

**Comment by ajmolstad** [comment]
If you just want to run the script, you can plug in essentially any design matrix you'd like: it need not be real genotype data or an RDS file.  It would probably be easier to discuss this over email at amolstad@ufl.edu.

**Comment by amiloudij** [comment]
I sent you an email. If you can send me a genotype matrix file that it can works with the code... Thanks
